package outline

import format "github.com/fabianoflorentino/aprendago/outline/format"

func BemVindo() {
	topic := format.OutlineContent{
		Title: "Bem-vindo",
		Content: `
- Bem vindo ao curso!
- Eu sou...
- Go foi criado por gente foda que criou o Unix, B, UTF-8...
- Em 2006 o google queria...
- É uma lingguagem que vem crescrendo horrores...
- Nesse curso você vai aprender...
- O curriculo que vamos estudar...
- Para os novos na programação... Para os programadores experientes...
- Participe!
`,
	}

	format.FormatOutlineTopic(topic)
}
