name: Trivy vulnerability scan

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docs/**'
      - '.github/**'

jobs:
  scan:
    name: Trivy vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          output: scan.out
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: 'CRITICAL,HIGH'

      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s scan.out ]]; then
            {
              echo "## Trivy Vulnerability Scan"
              echo "<details><summary>Click to see the Trivy vulnerability scan results</summary>"
              echo ""
              echo '```go'
              cat scan.out
              echo '```'
              echo "</details>"
            } >> $TRIVY_SCAN_SUMMARY
          fi
